export const c = {
  bg: "#0f0f0f",
  surface: "#212121",
  elevated: "#272727",
  border: "#3f3f3f",
  borderFaint: "#2a2a2a",
  text: "#ffffff",
  muted: "#aaaaaa",
  hint: "#aeaeae",
  accent: "#5eaff5",
  accentDim: "#1a2940",
  accentBorder: "#2a4a6b",
  errText: "#ff6b6b",
  errBg: "#2d1515",
  errBorder: "#5c2020",
  okText: "#4ade80",
  okBg: "#152d1a",
  okBorder: "#1e5c30",
  warnText: "#fbbf24",
  warnBg: "#2d2010",
  warnBorder: "#5c4010",
};

export const s = {
  page: {
    fontFamily: "'DM Sans', sans-serif",
    minHeight: "100vh",
    background: c.bg,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  card: {
    background: c.surface,
    border: `0.5px solid ${c.border}`,
    borderRadius: 16,
    padding: "32px 28px",
    width: "100%",
    maxWidth: 380,
  },
  title: {
    fontSize: 18,
    fontWeight: 500,
    color: c.text,
    marginBottom: 4,
    fontFamily: "'DM Mono', monospace",
  },
  sub: { fontSize: 12, color: c.hint, marginBottom: 24 },
  btn: {
    width: "100%",
    padding: "10px 16px",
    borderRadius: 8,
    border: "none",
    background: c.accent,
    color: "#0f0f0f",
    fontSize: 13,
    fontWeight: 500,
    fontFamily: "'DM Sans', sans-serif",
    cursor: "pointer",
    transition: "opacity 0.15s",
  },
  ghost: { background: "transparent", border: `0.5px solid ${c.border}`, color: c.muted },
  err: {
    fontSize: 12,
    color: c.errText,
    background: c.errBg,
    border: `0.5px solid ${c.errBorder}`,
    borderRadius: 8,
    padding: "8px 12px",
  },
  ok: {
    fontSize: 12,
    color: c.okText,
    background: c.okBg,
    border: `0.5px solid ${c.okBorder}`,
    borderRadius: 8,
    padding: "8px 12px",
  },
  link: {
    background: "none",
    border: "none",
    color: c.accent,
    fontSize: 12,
    cursor: "pointer",
    padding: 0,
    fontFamily: "'DM Sans', sans-serif",
  },
};
